name: Fullstack Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd ${{ secrets.EC2_PATH }}

          echo "🔄 Pulling latest code"
          git pull origin main

          echo "🐍 Backend setup"
          cd backend
          source venv/bin/activate
          pip install -r requirements.txt
          pm2 restart backend

          echo "⚛️ Frontend build"
          cd ../work-updates
          npm install
          npm run build

          echo "🌐 Deploy to nginx"
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/

          sudo systemctl restart nginx

          echo "✅ Deployment done"

          EOF
